### ISSUE TITLE
Tectonic compatibility? 

### ISSUE THREAD

**Issue by angeerey** [WunderFunct/WFCaveOverhaul#1]
Not an issue but a question, is this mod compatible with Tectonic in any way? Both mods do work together, no problems with that, but I am wondering if Tectonic's custom cave generation overlaps with the changes WF's Cave Overhaul includes; lava rivers, for example. Whilst playing with both mods installed, I can't tell if I am mainly seeing Tectonic's or WF's cave generation, or maybe both.

**Comment by WunderFunct** [comment]
Thanks for asking!

WF's Cave Overhaul replaces the code used for specifically cave generation. That said, it appears that Tectonic's cave generation, ironically, is not included in the cave generation of Minecraft when Minecraft compiles its final mathematical equations for how the world should be generated. Weird, I know, but I've tested the generation of Tectonic caves in the current release of WF's Cave Overhaul and see no impact. 

But just incase there are unforeseen consequences with the current method, 1.3.x will contain a patch that surgically replaces the exact fingerprint of Minecraft's caves instead of blindly replacing the entire cave layer. 

Hope that helps.

Best,
W.F.
