### ISSUE TITLE
[1.20.1 Request] Add proper Modern Beta support.

### ISSUE THREAD

**Issue by Cixon** [WunderFunct/WFCaveOverhaul#6]
Source to mod:
https://www.curseforge.com/minecraft/mc-mods/modern-beta

open-source too, i believe. the dev for this mod has been on a long hiatus. i played with your mod and modern's a bit.
there were some issues found. a broad amount features work such as mine intersection and river of lavas BUT -- i do not see **any large expansive caves** or **lava falls**.

this was tested using the modern_beta:modern_beta world-type followed by using "biomeProvider": "voronoi" setting.

**Comment by WunderFunct** [comment]
Noted. I'm working on a series of compat patches. I'll add modern beta to the list of mods I'm verifying compatibility for.

**Comment by WunderFunct** [comment]
It looks like Modern Beta fundamentally alters aspects of the worldgen process, which is causing one of the mixins to crash. I *think* I've got a fix but it looks like it's a lot of work at this time. I'll put it on the docket for 1.3.4/1.4. If my fix works, it'll be patched in 1.3.4 or 1.4.

Quick clarification: this is testing against the current CO codebase which includes a new way to check if worldgen is occurring in the overworld. During this test, I noticed some crashes, which is why I'm blabbering on about crashes :)

Regarding your feature request, 1.3.2+ includes an option to enable default worldgen alongside CO; you'll need to use that. Lavafalls are a rare occurrence due to how CO works, but I plan to change how lavafalls work in the future to make them more common.

**Comment by WunderFunct** [comment]
Quick update, modern beta support needs to be shelved. MB appears to completely re-write major parts of Minecraft's worldgen, so my noise overrides don't have a chance to run. I'd have to formally set up CO as an MB mod in a sense, which is doable but a big timesink.

I'm closing this ticket. I'm sorry for this situation since I'd like to play on a world that has MB + CO one day.
